apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      containers:
        - image: sissbruecker/linkding:1.31.0
          name: linkding
          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: /app/data
              name: linkding-data-svc
      volumes:
        - name: linkding-data-svc
          persistentVolumeClaim:
            claimName: linkding-data-svc
